import { MigrationInterface, QueryRunner } from "typeorm";

export class migrations1655181728870 implements MigrationInterface {
	public async up(queryRunner: QueryRunner): Promise<void> {
		queryRunner.query(`
        
        insert into public.user ("firstName", "lastName", email, password, username, "totalPoints") values ('Latrina', 'Skerritt', 'lskerritt0@dyndns.org', 'muyzLvpXutu', 'lskerritt0', 36);
insert into public.user ("firstName", "lastName", email, password, username, "totalPoints") values ('Mariejeanne', 'Philpotts', 'mphilpotts1@salon.com', '3zy8S4WDfwM', 'mphilpotts1', 32);
insert into public.user ("firstName", "lastName", email, password, username, "totalPoints") values ('Sydel', 'Ruske', 'sruske2@engadget.com', 'ZSzbHaQxW', 'sruske2', 68);
insert into public.user ("firstName", "lastName", email, password, username, "totalPoints") values ('Katha', 'Arnauduc', 'karnauduc3@omniture.com', 'EZys1eKyAl0V', 'karnauduc3', 86);
insert into public.user ("firstName", "lastName", email, password, username, "totalPoints") values ('Dino', 'Castleman', 'dcastleman4@narod.ru', 'fpgNUFqjxiQk', 'dcastleman4', 100);
insert into public.user ("firstName", "lastName", email, password, username, "totalPoints") values ('Jillane', 'Kupker', 'jkupker5@mysql.com', 'HkWUty5', 'jkupker5', 86);
insert into public.user ("firstName", "lastName", email, password, username, "totalPoints") values ('Tedd', 'Stuckley', 'tstuckley6@cisco.com', '2vZsV9n', 'tstuckley6', 12);
insert into public.user ("firstName", "lastName", email, password, username, "totalPoints") values ('Indira', 'Demkowicz', 'idemkowicz7@patch.com', '3iOTRL3Mn', 'idemkowicz7', 60);
insert into public.user ("firstName", "lastName", email, password, username, "totalPoints") values ('Gertrudis', 'Corsor', 'gcorsor8@delicious.com', 'EeUZSh3FTnP', 'gcorsor8', 84);
insert into public.user ("firstName", "lastName", email, password, username, "totalPoints") values ('Kalie', 'Baysting', 'kbaysting9@alexa.com', 'XhJl7Xl91', 'kbaysting9', 4);
insert into public.user ("firstName", "lastName", email, password, username, "totalPoints") values ('Dugald', 'Macourek', 'dmacoureka@independent.co.uk', 'KKQng6WVjo0', 'dmacoureka', 19);
insert into public.user ("firstName", "lastName", email, password, username, "totalPoints") values ('Dode', 'Rubanenko', 'drubanenkob@cdc.gov', '7dHwg58C', 'drubanenkob', 63);
insert into public.user ("firstName", "lastName", email, password, username, "totalPoints") values ('Christoffer', 'Cosin', 'ccosinc@howstuffworks.com', 'gv71tpbLrFJq', 'ccosinc', 31);
insert into public.user ("firstName", "lastName", email, password, username, "totalPoints") values ('Pincus', 'Paye', 'ppayed@squarespace.com', 'aiCMBlky1Z', 'ppayed', 94);
insert into public.user ("firstName", "lastName", email, password, username, "totalPoints") values ('Hew', 'Stoyles', 'hstoylese@flickr.com', '8aG97yvd', 'hstoylese', 57);
insert into public.user ("firstName", "lastName", email, password, username, "totalPoints") values ('Jo', 'Rosson', 'jrossonf@cisco.com', '2tKYnRCbXW', 'jrossonf', 24);
insert into public.user ("firstName", "lastName", email, password, username, "totalPoints") values ('Jameson', 'Elsey', 'jelseyg@yale.edu', '2HA9Mi', 'jelseyg', 53);
insert into public.user ("firstName", "lastName", email, password, username, "totalPoints") values ('Illa', 'Barthelmes', 'ibarthelmesh@blogger.com', 'CAWzYf', 'ibarthelmesh', 18);
insert into public.user ("firstName", "lastName", email, password, username, "totalPoints") values ('Kathleen', 'Bussey', 'kbusseyi@deliciousdays.com', 'hi6oP8ueeBld', 'kbusseyi', 74);
insert into public.user ("firstName", "lastName", email, password, username, "totalPoints") values ('Lora', 'de la Tremoille', 'ldelatremoillej@utexas.edu', 'CqJwHpXxQac', 'ldelatremoillej', 65);
insert into public.user ("firstName", "lastName", email, password, username, "totalPoints") values ('Loella', 'Petracco', 'lpetraccok@cmu.edu', 'L89hjJLY', 'lpetraccok', 90);
insert into public.user ("firstName", "lastName", email, password, username, "totalPoints") values ('Hattie', 'Shackel', 'hshackell@prlog.org', 'yPvA2W', 'hshackell', 43);
insert into public.user ("firstName", "lastName", email, password, username, "totalPoints") values ('Leonelle', 'Kropach', 'lkropachm@aboutads.info', 'NIGa2wcpvOMu', 'lkropachm', 25);
insert into public.user ("firstName", "lastName", email, password, username, "totalPoints") values ('Gino', 'Ianiello', 'gianiellon@dmoz.org', 'SWbaFx', 'gianiellon', 14);
insert into public.user ("firstName", "lastName", email, password, username, "totalPoints") values ('Leigh', 'Meneghi', 'lmeneghio@mlb.com', 'GD54EU9I4', 'lmeneghio', 10);
insert into public.user ("firstName", "lastName", email, password, username, "totalPoints") values ('Loralie', 'Giercke', 'lgierckep@photobucket.com', '8XaHDuCaLoC1', 'lgierckep', 59);
insert into public.user ("firstName", "lastName", email, password, username, "totalPoints") values ('Cathleen', 'Goldthorpe', 'cgoldthorpeq@hibu.com', 'S6wXFiM', 'cgoldthorpeq', 42);
insert into public.user ("firstName", "lastName", email, password, username, "totalPoints") values ('Kandace', 'Sheardown', 'ksheardownr@mayoclinic.com', 'jD9qwv5', 'ksheardownr', 98);
insert into public.user ("firstName", "lastName", email, password, username, "totalPoints") values ('Nita', 'Preist', 'npreists@wikispaces.com', '5TnAR9y4', 'npreists', 98);
insert into public.user ("firstName", "lastName", email, password, username, "totalPoints") values ('Hilliary', 'Abrahmer', 'habrahmert@un.org', '4bRgLy0bbs', 'habrahmert', 90);
insert into public.user ("firstName", "lastName", email, password, username, "totalPoints") values ('Del', 'Clail', 'dclailu@booking.com', 'rYKXsz6H5Os', 'dclailu', 59);
insert into public.user ("firstName", "lastName", email, password, username, "totalPoints") values ('Bendicty', 'Volk', 'bvolkv@w3.org', 'R0uJsjm', 'bvolkv', 22);
insert into public.user ("firstName", "lastName", email, password, username, "totalPoints") values ('Niccolo', 'Pringer', 'npringerw@mtv.com', 'DFwH7C', 'npringerw', 59);
insert into public.user ("firstName", "lastName", email, password, username, "totalPoints") values ('Thadeus', 'Duthy', 'tduthyx@edublogs.org', 'XnIyz5JdU', 'tduthyx', 95);
insert into public.user ("firstName", "lastName", email, password, username, "totalPoints") values ('Christoffer', 'Frounks', 'cfrounksy@1und1.de', 'B5mmvG6f5v', 'cfrounksy', 43);
insert into public.user ("firstName", "lastName", email, password, username, "totalPoints") values ('Pearce', 'Daldry', 'pdaldryz@engadget.com', 'yA8EIt0jBtTF', 'pdaldryz', 20);
insert into public.user ("firstName", "lastName", email, password, username, "totalPoints") values ('Emmey', 'MacGorley', 'emacgorley10@answers.com', 'SET52LOLy', 'emacgorley10', 34);
insert into public.user ("firstName", "lastName", email, password, username, "totalPoints") values ('Mamie', 'Godin', 'mgodin11@unblog.fr', 'eAI9xgBPK', 'mgodin11', 64);
insert into public.user ("firstName", "lastName", email, password, username, "totalPoints") values ('Lucila', 'Ambrus', 'lambrus12@patch.com', 'F5l76Q', 'lambrus12', 51);
insert into public.user ("firstName", "lastName", email, password, username, "totalPoints") values ('Karol', 'Renowden', 'krenowden13@sogou.com', 'PKL8CpqjRO', 'krenowden13', 53);
insert into public.user ("firstName", "lastName", email, password, username, "totalPoints") values ('Walther', 'Stoade', 'wstoade14@wikispaces.com', 'rp0CLeOd', 'wstoade14', 26);
insert into public.user ("firstName", "lastName", email, password, username, "totalPoints") values ('Josephina', 'Damato', 'jdamato15@cbsnews.com', '4g2JNJnPDH4', 'jdamato15', 23);
insert into public.user ("firstName", "lastName", email, password, username, "totalPoints") values ('Aurlie', 'Staynes', 'astaynes16@smh.com.au', 'V8Lktvn6WM', 'astaynes16', 10);
insert into public.user ("firstName", "lastName", email, password, username, "totalPoints") values ('Vladimir', 'Diter', 'vditer17@utexas.edu', 'QjPDDmJoA', 'vditer17', 26);
insert into public.user ("firstName", "lastName", email, password, username, "totalPoints") values ('Raphaela', 'Balazin', 'rbalazin18@icio.us', 'ZrRtVQm8m9', 'rbalazin18', 24);
insert into public.user ("firstName", "lastName", email, password, username, "totalPoints") values ('Kerry', 'Hune', 'khune19@vimeo.com', 'MbcavkSA', 'khune19', 86);
insert into public.user ("firstName", "lastName", email, password, username, "totalPoints") values ('Darcey', 'Thomkins', 'dthomkins1a@springer.com', 'E3sygKnIWzZB', 'dthomkins1a', 97);
insert into public.user ("firstName", "lastName", email, password, username, "totalPoints") values ('Osbert', 'Mealand', 'omealand1b@behance.net', '8BPtLQcXDj1G', 'omealand1b', 91);
insert into public.user ("firstName", "lastName", email, password, username, "totalPoints") values ('Briney', 'Challens', 'bchallens1c@springer.com', '8OgDaE', 'bchallens1c', 6);
insert into public.user ("firstName", "lastName", email, password, username, "totalPoints") values ('Bondie', 'Boyne', 'bboyne1d@seesaa.net', 'cpJXpalEW', 'bboyne1d', 36);
insert into public.user ("firstName", "lastName", email, password, username, "totalPoints") values ('Martie', 'Eldin', 'meldin1e@elpais.com', 'oMWk4TLSwn', 'meldin1e', 97);
insert into public.user ("firstName", "lastName", email, password, username, "totalPoints") values ('Gypsy', 'Rosewall', 'grosewall1f@jugem.jp', 'YWwTEN9djBNv', 'grosewall1f', 95);
insert into public.user ("firstName", "lastName", email, password, username, "totalPoints") values ('Claudius', 'Alster', 'calster1g@telegraph.co.uk', '8GB9mDMm10', 'calster1g', 91);
insert into public.user ("firstName", "lastName", email, password, username, "totalPoints") values ('Gustaf', 'Videan', 'gvidean1h@godaddy.com', 'mWBGR3r5L3w', 'gvidean1h', 30);
insert into public.user ("firstName", "lastName", email, password, username, "totalPoints") values ('Daveta', 'O''Carrol', 'docarrol1i@statcounter.com', 'kx8750Ey3S7', 'docarrol1i', 78);
insert into public.user ("firstName", "lastName", email, password, username, "totalPoints") values ('Fionna', 'Botterman', 'fbotterman1j@smh.com.au', 'fzWF7rqvv', 'fbotterman1j', 27);
insert into public.user ("firstName", "lastName", email, password, username, "totalPoints") values ('Lance', 'Goodburn', 'lgoodburn1k@sfgate.com', 'tAkP2MRB', 'lgoodburn1k', 19);
insert into public.user ("firstName", "lastName", email, password, username, "totalPoints") values ('Mariejeanne', 'Thumnel', 'mthumnel1l@biblegateway.com', 'DVKiKaA', 'mthumnel1l', 76);
insert into public.user ("firstName", "lastName", email, password, username, "totalPoints") values ('Artus', 'Saunt', 'asaunt1m@sphinn.com', 'IrPpQpsQ6o', 'asaunt1m', 6);
insert into public.user ("firstName", "lastName", email, password, username, "totalPoints") values ('Editha', 'Roubay', 'eroubay1n@businessinsider.com', 'S79ioFJjD', 'eroubay1n', 64);
insert into public.user ("firstName", "lastName", email, password, username, "totalPoints") values ('Kara', 'Hagwood', 'khagwood1o@who.int', 'uDz08t', 'khagwood1o', 81);
insert into public.user ("firstName", "lastName", email, password, username, "totalPoints") values ('Cate', 'Komorowski', 'ckomorowski1p@aol.com', 'GluGHgIFq0G', 'ckomorowski1p', 56);
insert into public.user ("firstName", "lastName", email, password, username, "totalPoints") values ('Boot', 'Juggins', 'bjuggins1q@amazon.de', 'BZnjiAZ', 'bjuggins1q', 51);
insert into public.user ("firstName", "lastName", email, password, username, "totalPoints") values ('Duke', 'Phorsby', 'dphorsby1r@odnoklassniki.ru', 'vPUsNYn', 'dphorsby1r', 25);
insert into public.user ("firstName", "lastName", email, password, username, "totalPoints") values ('Chandra', 'Barrs', 'cbarrs1s@fema.gov', 'dm3C4W4Vdi4', 'cbarrs1s', 97);
insert into public.user ("firstName", "lastName", email, password, username, "totalPoints") values ('Anni', 'Ferrini', 'aferrini1t@ebay.com', 'a99QY0eb', 'aferrini1t', 6);
insert into public.user ("firstName", "lastName", email, password, username, "totalPoints") values ('Jimmy', 'Creelman', 'jcreelman1u@behance.net', 'pUHsSUW1B', 'jcreelman1u', 29);
insert into public.user ("firstName", "lastName", email, password, username, "totalPoints") values ('Oberon', 'Vigne', 'ovigne1v@360.cn', 'W6hiNrKzJWw', 'ovigne1v', 95);
insert into public.user ("firstName", "lastName", email, password, username, "totalPoints") values ('Joy', 'Dallin', 'jdallin1w@upenn.edu', 'THhz2h8', 'jdallin1w', 26);
insert into public.user ("firstName", "lastName", email, password, username, "totalPoints") values ('Quinlan', 'Gillow', 'qgillow1x@state.gov', 'wOmzuMKMv4', 'qgillow1x', 73);
insert into public.user ("firstName", "lastName", email, password, username, "totalPoints") values ('Jacquelin', 'Samson', 'jsamson1y@upenn.edu', '5kwBNiWx', 'jsamson1y', 36);
insert into public.user ("firstName", "lastName", email, password, username, "totalPoints") values ('Kariotta', 'Gluyus', 'kgluyus1z@indiatimes.com', 'wKHCPd1', 'kgluyus1z', 35);
insert into public.user ("firstName", "lastName", email, password, username, "totalPoints") values ('Bartie', 'Fullilove', 'bfullilove20@ezinearticles.com', 'k3aPJTB2TVwa', 'bfullilove20', 11);
insert into public.user ("firstName", "lastName", email, password, username, "totalPoints") values ('Harold', 'MacKilroe', 'hmackilroe21@pinterest.com', 'rNRMOn7', 'hmackilroe21', 54);
insert into public.user ("firstName", "lastName", email, password, username, "totalPoints") values ('Kate', 'McVicker', 'kmcvicker22@smugmug.com', 'HKRpQoW92', 'kmcvicker22', 38);
insert into public.user ("firstName", "lastName", email, password, username, "totalPoints") values ('Carlita', 'Franceschi', 'cfranceschi23@biglobe.ne.jp', '9wVd8sUdre', 'cfranceschi23', 29);
insert into public.user ("firstName", "lastName", email, password, username, "totalPoints") values ('Sebastian', 'Sawforde', 'ssawforde24@nsw.gov.au', 'PahnHPd3dhV', 'ssawforde24', 31);
insert into public.user ("firstName", "lastName", email, password, username, "totalPoints") values ('Kenyon', 'Behnke', 'kbehnke25@typepad.com', 'CsGnLHkG9yO', 'kbehnke25', 3);
insert into public.user ("firstName", "lastName", email, password, username, "totalPoints") values ('Tommy', 'Stride', 'tstride26@redcross.org', 'juZJ0g3h1YZg', 'tstride26', 77);
insert into public.user ("firstName", "lastName", email, password, username, "totalPoints") values ('Gaile', 'Spybey', 'gspybey27@whitehouse.gov', 'SGhNYqkz', 'gspybey27', 37);
insert into public.user ("firstName", "lastName", email, password, username, "totalPoints") values ('Viviyan', 'Bruno', 'vbruno28@oakley.com', 'caXvXgd26kV', 'vbruno28', 97);
insert into public.user ("firstName", "lastName", email, password, username, "totalPoints") values ('Jozef', 'Androletti', 'jandroletti29@yahoo.com', 'jcOZX6', 'jandroletti29', 100);
insert into public.user ("firstName", "lastName", email, password, username, "totalPoints") values ('Stacy', 'Gatman', 'sgatman2a@statcounter.com', 'r1PsSQ', 'sgatman2a', 24);
insert into public.user ("firstName", "lastName", email, password, username, "totalPoints") values ('Keane', 'Kristufek', 'kkristufek2b@symantec.com', 'QLlZoYZPCo', 'kkristufek2b', 88);
insert into public.user ("firstName", "lastName", email, password, username, "totalPoints") values ('Calida', 'Kalberer', 'ckalberer2c@arstechnica.com', '6GvF8hpqJi', 'ckalberer2c', 14);
insert into public.user ("firstName", "lastName", email, password, username, "totalPoints") values ('Efren', 'Dutch', 'edutch2d@cisco.com', 'tyWNnHn', 'edutch2d', 84);
insert into public.user ("firstName", "lastName", email, password, username, "totalPoints") values ('Miriam', 'Highton', 'mhighton2e@amazon.de', 'NOAIQGUd6fOH', 'mhighton2e', 75);
insert into public.user ("firstName", "lastName", email, password, username, "totalPoints") values ('Alonso', 'Willarton', 'awillarton2f@simplemachines.org', '98SKNjSQ0FI7', 'awillarton2f', 67);
insert into public.user ("firstName", "lastName", email, password, username, "totalPoints") values ('Johanna', 'Wrixon', 'jwrixon2g@w3.org', 'G5I3qVXiJ5C', 'jwrixon2g', 44);
insert into public.user ("firstName", "lastName", email, password, username, "totalPoints") values ('Ivar', 'Bodega', 'ibodega2h@themeforest.net', '5zehFCgRn', 'ibodega2h', 74);
insert into public.user ("firstName", "lastName", email, password, username, "totalPoints") values ('Phineas', 'Boleyn', 'pboleyn2i@pagesperso-orange.fr', 'I5a2zQUxq4l', 'pboleyn2i', 58);
insert into public.user ("firstName", "lastName", email, password, username, "totalPoints") values ('Hayley', 'Bullan', 'hbullan2j@github.io', 'NmVqdZI', 'hbullan2j', 30);
insert into public.user ("firstName", "lastName", email, password, username, "totalPoints") values ('Vikki', 'Hawket', 'vhawket2k@ovh.net', 'YvsozNe', 'vhawket2k', 3);
insert into public.user ("firstName", "lastName", email, password, username, "totalPoints") values ('Shermy', 'Olford', 'solford2l@google.de', 'YdyGrg', 'solford2l', 15);
insert into public.user ("firstName", "lastName", email, password, username, "totalPoints") values ('Neill', 'Rawles', 'nrawles2m@deliciousdays.com', 'KunkF6QK', 'nrawles2m', 12);
insert into public.user ("firstName", "lastName", email, password, username, "totalPoints") values ('Jarid', 'Bugge', 'jbugge2n@whitehouse.gov', 'jCnXTEs6yvCg', 'jbugge2n', 44);
insert into public.user ("firstName", "lastName", email, password, username, "totalPoints") values ('Edsel', 'Chevolleau', 'echevolleau2o@homestead.com', 'FAenzrUPZE', 'echevolleau2o', 49);
insert into public.user ("firstName", "lastName", email, password, username, "totalPoints") values ('Margo', 'Lindback', 'mlindback2p@illinois.edu', 'Og8dbVi8GDG', 'mlindback2p', 82);
insert into public.user ("firstName", "lastName", email, password, username, "totalPoints") values ('Bronson', 'Sunley', 'bsunley2q@amazon.co.uk', 'y88Lifd', 'bsunley2q', 9);
insert into public.user ("firstName", "lastName", email, password, username, "totalPoints") values ('Madge', 'Tordoff', 'mtordoff2r@w3.org', '9YFculKa6', 'mtordoff2r', 82);
`);
	}

	public async down(_queryRunner: QueryRunner): Promise<void> {}
}
